use super::types::StampMeta;

pub const FRONTMATTER_STAMP_KEY: &str = "x_generated";
pub const JSON_STAMP_FIELD: &str = "x_generated";

pub const COMMENT_STAMP_PREFIX: &str = "<!-- @generated by agents: ";
pub const COMMENT_STAMP_SUFFIX: &str = " -->";

pub fn encode_stamp_meta_json(meta: &StampMeta) -> Result<String, serde_json::Error> {
    serde_json::to_string(meta)
}

pub fn encode_comment_stamp_line(meta: &StampMeta) -> Result<String, serde_json::Error> {
    let json = encode_stamp_meta_json(meta)?;
    Ok(format!(
        "{}{}{}\n",
        COMMENT_STAMP_PREFIX, json, COMMENT_STAMP_SUFFIX
    ))
}
